### PR TITLE
New mongo scheme

### PR DESCRIPTION
**Pull request by pglock**
I started working on the new mongo db api, that saves each annotation as an object.

See issue #64 

The "/api"  get request returns a list of annotations for a given `file_id` and `user_id`.
How should the server config be handled? For the time I added a "server_config.json".

### CODE REVIEW

**Comment by r03ert0** [comment]
hi @pglock !
Our eslint boss is happier when you use camelCase instead of using_underscores : p

**Comment by r03ert0** [comment]
@pglock,

In `app.js`:

* I'd suggest using `serverConfig` instead of `server_config`, same for `fileID` and `userID`
* instead of `for (var i`, define `var i` on the top of the function and do just `for (i` in the code
* we'll be using `i += 1` instead of `i++`

In general, make sure to run `eslint app.j`, so that we can have an homogeneous coding style (the coding style rules are in the hidden file `.eslintrc.js`).

the file `server_config.json` contains a juelich address. I'd suggest doing as in our other example files: create a `server_config.json.example` with the `localhost` address and add your own `server_config.json` file to .gitignore.

looking forward to merge that PR ! :D

**Comment by pglock** [comment]
thanks for your feedback! All of your remarks should be fixed now.
The "/api" post request saves one annotation now. 

Todo:

- refactor microdraw.js to use the new api
- write tests for the api requests
- the post request can save multiple annotations at once

**Comment by r03ert0** [comment]
oh my... that PR breaks all the load/save...

**Comment by r03ert0** [comment]
hi @pglock !

I changed a few things to get it working again:
* I moved back to saving all regions in a slice, because the contrary would require a few changes in microdraw.js that are not yet there
* To keep the consistency of the client and the server I changed `fileID` into `source`
* The user name is obtained at the server base on the current login, and not recover from the client (nothing would prevent a relatively js-aware user from impersonating another one by just iinjecting the appropriate code)
* I'm removing the `brainID` fields: the `.json` files pointed by the `source` tags can already contain references to a set of many slices, and having a supplementary `brainID` seems redundant. I may be wrong, though... we could add `brainID` back, in which case I'd prefer to call it something more neutral, like `sectionSet` or something, because microdraw is specific to brain data

now microdraw is back working \o/

**Pull request merged**
