### PR TITLE
feat: added API tests

### PR DESCRIPTION
**Pull request by xgui3783**
- [x] Run `npm test` successfully. 
- [x] Run `npm run mocha`successfully.

- [ x `test_screenshots` generates the same test pictures in `test` as there were in `test/reference` and does not show any errors

- [x] I implemented tests for the new changes OR
- [ ] These changes do not require tests because _____

- [ ] These changes fix #__ (github issue number if applicable).

### CODE REVIEW

**Comment by xgui3783** [comment]
don't merge yet. making some changes to `README.md`

**Comment by r03ert0** [comment]
what's the use of save annotation without data? From the readme:

```
# save annotation
POST /api?source=/path/to/file&slice=12token=FAKE_TOKEN
```

**Comment by xgui3783** [comment]
should have added `-d`?

I wasn't too sure if I should be using curl :o 

I will update with curl syntax

**Comment by xgui3783** [comment]
the resolved conflicts introduced some failed tests. I will take a look why when I get a chance.

**Comment by katjaq** [comment]
Thank you!

**Comment by r03ert0** [comment]
should we merge this PR?

**Comment by xgui3783** [comment]
Would be good. 😀

**Pull request merged**
