### PR TITLE
Make eslint happy :)

### LINKED ISSUE #69: make eslint happy
MicroDraw uses eslint for establishing a common code style.

We are currently at 447 complaints by eslint... :D wayyyyy to goooo!!! 
It also helps us detect where function descriptions for docjs would still be missing.

### PR DESCRIPTION
**Pull request by jackiemacharia**
---

- [X] `screenshot_test_walk` generates the same test pictures as there were and does not show any errors
- [X] These changes fix #69 (github issue number if applicable).
- [X] All MicroDraw tools behave as expected:
    * **GESTURES**
        - [X] zoom in and out with two finger drag works
    * **KEYS**
        * right and up arrow key or left and down arrow key
            - [X] jump to next or previous slice respectively
            - [X] update the slider accordingly
            - [X] update the slice number accordingly 
        * cmd z undoes
            - [X] any step back that you have done in their chronological order including
            - [X] translation of region
            - [X] drawing region
            - [X] adding point
            - [X] deleting point
        to be completed (maybe it is implemented and working for all functions, so we can delete the single step checks)
    * **TOOL BUTTONS**
        * red rectangle in navigation window 
            - [X] corresponds to tissue piece selected in viewer
            - [X] can be moved upon mouse down drag
        * navigation tool 
            - [X] moves the slice inside the viewer upon on mouse down drag
        to be continued...
        
            

- [ ] I implemented tests for these changes OR
- [X] These changes do not require tests because they fix code styling errors

### CODE REVIEW

**Comment by r03ert0** [comment]
thank you very much @jackiemacharia !!

what is the effect of adding `/public` to `.eslintignore`?

...we'd still want to lint the js code inside `/public` (in particular, we're right now fighting with `microdraw.js`).

if it's ok, would you remove `/public` from `.eslintignore`?

looking forward to merge your PR!

**Comment by jackiemacharia** [comment]
@r03ert0 aha, what I should actually have ignored is `public/**/*.min.js, what do you think? Updating in a bit.

**Comment by r03ert0** [comment]
awesome, thank you :D

**Comment by r03ert0** [comment]
hi @jackiemacharia !

The `app.js` code wasn't getting the right value into `body` after the object destructuring you added, which looked like:

```
var {body} = req.body;
```

...the value of body was just `undefined` after the assignment. I've never used object destructuring before, but looking into the eslint page (<https://eslint.org/docs/rules/prefer-destructuring>), I replaced that line with:

```
var {body: body} = req;
```
and that works. Do you know what may be the error?

**Comment by jackiemacharia** [comment]
@r03ert0 aah I think I see what is going on with the destructuring.  Was wondering why not 
`var {body} = req;` though. But it seems with destructuring we'd need to explicitly reassign the current key to the new key, hence `{body: body}`.

Raising a quick PR to fix L4 of `controller/data/data.controller.js` as well.

**Comment by xgui3783** [comment]
hmm, `var { body } = req` should work just fine, and would assign body as
req.body. Correct me if I am wrong, but `var { body_ : body } = req` would
assign req.body as body_

**Pull request merged**
