### PR TITLE
added onDeselet for tool methods, moved drawpolygon ondeselect from m…

### PR DESCRIPTION
**Pull request by xgui3783**
…icrodraw.js to tools/drawPolygon.js

In our use cases, there are often needs to have a callback when the tool is deselected. This PR implements a `onDeslect` method of the tools, that will be called when user selects a new tool. 

I have also partially patched `drawPolygon.js`, which can somewhat take advantage of the newly implemented method. 

The undo of individual points on the polygon has been temporarily disabled in this PR, as we have encountered some strange behaviours, which can be reproduced:
- use polygon tool draw a > 4 sided object
- select a different tool
- ctrl z

In this PR, ctrlZ will reset entire polygons. 

I would welcome any discussion on the behaviour of the polygon and make any changes. 

---

- [x] `screenshot_test_walk` generates the same test pictures as there were and does not show any errors
- [ ] These changes fix #__ (github issue number if applicable).
- [x] All MicroDraw tools behave as expected:
    * **GESTURES**
        - [ ] zoom in and out with two finger drag works
    * **KEYS**
        * right and up arrow key or left and down arrow key
            - [ ] jump to next or previous slice respectively
            - [ ] update the slider accordingly
            - [ ] update the slice number accordingly
        * cmd z undoes
            - [ ] any step back that you have done in their chronological order including
            - [ ] translation of region
            - [ ] drawing region
            - [ ] adding point
            - [ ] deleting point
        to be completed (maybe it is implemented and working for all functions, so we can delete the single step checks)
    * **TOOL BUTTONS**
        * red rectangle in navigation window
            - [ ] corresponds to tissue piece selected in viewer
            - [ ] can be navigated upon mouse down drag
        * navigation tool
            - [ ] navigates the slice inside the viewer upon mouse down drag
        * home button
            - [ ] zooms out to view the data in full screen size view
        * zoomIn tool
            - [ ] zooms one step in upon click
        * zoomOut tool
            - [ ] zooms one step out upon click
        * left arrow
            - [ ] jumps to the previous slice
        * right arrow
            - [ ] jumps to the next slice
        * select tool
            - [ ] selects a region upon click
        * draw tool
            - [ ] draws a new region as bezier curve
        * drawPolygon tool
            - [x] draws a new region as a polygon path
        * simplify tool
            - [ ] decreases the number of points in the region path while aiming at conserving the shape
        * addPoint tool
            - [ ] adds a point to the path upon click at position of mouse click
        * deletePoint tool
            - [ ] deletes a point from the path upon mouse click
        * addRegion tool
            - [ ] unifies two overlapping regions into one
        * deleteRegion tool
            - [ ] deletes a region upon click
        * splitRegion tool
            - [ ] splits one region at the intersection path with a second region
        * rotate tool
            - [ ] rotates a region around the point of mouse click
        * flip tool
            - [ ] flips a region around its vertical axis
        * toPolygon tool
            - [ ] converts the region path from bezier curve to polygon path
        * toBezier
            - [ ] converts the region path from polygon path to bezier curve
        * copy tool
            - [ ] copies a region
        * paste tool
            - [ ] pastes the copied region
        * save tool
            - [ ] saves the set of drawn regions to the database
        * screenshot tool
            - [ ] creates a screenshot of the data layer (not of the annotations yet) at a chosen resolution
        * delete tool
            - [ ] deletes the selected region
        * closeMenu tool
            - [ ] hides the menu bar upon click
        * openMenu tool
            - [ ] shows the menu bar upon click
        * undo tool
            - [ ] undoes the user's actions in reverse chronological order

- [ ] I implemented tests for these changes OR
- [x] These changes do not require tests because test already exists

### CODE REVIEW

**Comment by katjaq** [comment]
Hey! Thank you so much for all your work.

Before merging your PR, I would like to ask you for the following change: 
The `undo` should ideally always undo step by step, so if you undo once, it should undo the last thing action did. In the case of drawing a polygon, undo should just undo the placement of the last vertex, not of the entire polygon. (and a next undo should then undo the previous vertex and so on, and eventually the entire polygon).

Would it be possible for you to change this? 
Thank you so much again.

**Comment by xgui3783** [comment]
that makes total sense. 

should the the polygon tool be selected (if it is not already)?

the scenario I have in my mind is the following:

- user selects polygon tool
- user completes a square with the polygon tool, (solid square)  
- user selects free style drawing tool
- user presses `ctrl + z` / `cmd + z`
- square turns into a triangle

at this stage, IMHO, there are two modes modes of interaction, both makes some sense in their own way:

- square turns into a filled triangle, selected tool is still free style drawing. 
- square turns into a non-filled triangle, selected tool becomes polygon, and the user can finish the polygon

which mode makes sense to you?

**Comment by xgui3783** [comment]
I have made some changes to `drawpolygon.js`. Whilst it no longer implements `onDeselect` method, its beahviour is now more consistent with the desired behaviour, where a single `ctrl + z`  or `cmd + z` will result in the removal of a single dropped point. 

I hope the `onDeselect` functionality can remain though.

**Comment by katjaq** [comment]
Hey! that sounds great! I completely agree with your second scenario. The `cmd z` command should go one step back which means bringing back the unfinished polygon so that the user can finish it (which means : great to jump back to polygon tool being selected <3)

Many many thanks!!

**Pull request merged**
