### PR TITLE
Alternative multi-image undo with a single undo queue.

### PR DESCRIPTION
**Pull request by rdvincent**
This is an alternative implementation of multi-image undo that uses a single undo queue, tying each previous editing state to a specific image's annotations (implemented as a paper.js project). This means that actions taken on a slice can be undone while viewing another slice.

The undo operation should now assign the newly recreated paths to the correct project.

It is not clear to me which is really the better design from a user's point of view. Feel free to evaluate and use whichever one you prefer.

### CODE REVIEW

**Comment by r03ert0** [comment]
How does undo work in Display or Atelier 3D? Probably we should try to use the same paradigm. If display+a3d use single slice undo stack we go single slice; if they use multiple slice undo we go multiple... what do you think?

**Comment by rdvincent** [comment]
Display's undo works on any slice, similar to the code in the PR. This makes more sense in Display since annotations can be 3D and the user has a 3-axis view of the annotations. Not sure of the current state of A3D, as their undo functionality is still evolving.

**Comment by hspitzer** [comment]
I am not quite sure if I am happy about this - now I don't see what I am undoing... Would it be possible to move the focus the the section on which the undo is happening?

**Comment by rdvincent** [comment]
Of course we can do that - but ultimately the question is whether this is what the users of the tool would prefer.

**Pull request merged**
